name: Prettier Format

on:
  push:
    branches:
      - feat/add-prettier-check-actions # Replace with your main branch name

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Replace with the Node.js version you're using

      - name: Install Dependencies
        run: npm install # Or yarn install

      - name: Run Prettier
        run: npx prettier --write .
